"""Local config management commands."""

import sys
from pathlib import Path

import click
import yaml
from rich.console import Console

from ibxcli.core.config import DEFAULT_CONFIG_PATH
from ibxcli.core.client import IbxClient
from ibxcli.core.exceptions import IbxError

console = Console(stderr=True)
console_stdout = Console()

SAMPLE_CONFIG = """\
# ibx-cli configuration file
# Generated by: ibx config init
# File permissions should be: chmod 600

defaults:
  host: infoblox.example.com
  username: admin
  wapi_version: "2.13"
  ssl_verify: false
  timeout: 30
  max_results: 1000

# Named profiles override defaults
profiles:
  prod:
    host: infoblox-prod.example.com
    username: prod-admin
  lab:
    host: infoblox-lab.example.com
    username: lab-admin
    ssl_verify: false
"""


@click.group()
def config():
    """Local config management."""
    pass


@config.command("init")
def config_init():
    """Create a sample config file at ~/.infoblox/config."""
    cfg_path = DEFAULT_CONFIG_PATH
    if cfg_path.exists():
        console.print(f"[yellow]Config already exists at {cfg_path}[/yellow]")
        return

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(SAMPLE_CONFIG)
    console.print(f"[green]Created sample config at {cfg_path}[/green]")
    console.print("Edit it with your Infoblox connection details.")


@config.command("show")
@click.pass_context
def config_show(ctx):
    """Show the resolved configuration (password masked)."""
    from ibxcli.cli.main import _ensure_client
    _ensure_client(ctx)
    cfg = ctx.obj.get("config")
    if cfg is None:
        console.print("[red]No config available[/red]")
        return

    safe = {
        "host": cfg.host,
        "username": cfg.username,
        "password": "*" * len(cfg.password),
        "wapi_version": cfg.wapi_version,
        "ssl_verify": cfg.ssl_verify,
        "timeout": cfg.timeout,
        "max_results": cfg.max_results,
    }
    console_stdout.print(yaml.dump(safe, default_flow_style=False))


@config.command("test-connection")
@click.pass_context
def test_connection(ctx):
    """Test connection to Infoblox Grid Master."""
    from ibxcli.cli.main import _ensure_client
    _ensure_client(ctx)
    client: IbxClient = ctx.obj.get("client")
    if client is None:
        console.print("[red]No client available[/red]")
        sys.exit(1)

    console.print(f"Connecting to {client._connector.host}...")
    try:
        result = client.get("grid")
        if result:
            grid_name = result[0].get("name", "unknown")
            console.print(f"[green]Connected successfully![/green]")
            console.print(f"  Grid: {grid_name}")
            console.print(f"  WAPI version: {client._connector.wapi_version}")
        else:
            console.print("[yellow]Connected but no grid info returned[/yellow]")
    except IbxError as e:
        console.print(f"[red]Connection failed:[/red] {e}")
        sys.exit(1)
